//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCT.TT.CryptoInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCT.TT.CryptoInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додати в обране.
        /// </summary>
        public static string DetailCryptoPage_AddToFavorites_btn {
            get {
                return ResourceManager.GetString("DetailCryptoPage_AddToFavorites_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string DetailCryptoPage_Back_btn {
            get {
                return ResourceManager.GetString("DetailCryptoPage_Back_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поділитися.
        /// </summary>
        public static string DetailCryptoPage_Share_btn {
            get {
                return ResourceManager.GetString("DetailCryptoPage_Share_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новини.
        /// </summary>
        public static string MainWindow_News_btn {
            get {
                return ResourceManager.GetString("MainWindow_News_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Портфель.
        /// </summary>
        public static string MainWindow_Portfolio_btn {
            get {
                return ResourceManager.GetString("MainWindow_Portfolio_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Огляд.
        /// </summary>
        public static string MainWindow_Review_btn {
            get {
                return ResourceManager.GetString("MainWindow_Review_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Налаштування.
        /// </summary>
        public static string MainWindow_Setting_btn {
            get {
                return ResourceManager.GetString("MainWindow_Setting_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 24г %.
        /// </summary>
        public static string Page1_24h_tabel {
            get {
                return ResourceManager.GetString("Page1_24h_tabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список криптовалют.
        /// </summary>
        public static string Page1_ListOfCryptocurrencies_label {
            get {
                return ResourceManager.GetString("Page1_ListOfCryptocurrencies_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ринкова капітилізація.
        /// </summary>
        public static string Page1_MarketCapitalization_tabel {
            get {
                return ResourceManager.GetString("Page1_MarketCapitalization_tabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Огляд ринку.
        /// </summary>
        public static string Page1_MarketOverview_label {
            get {
                return ResourceManager.GetString("Page1_MarketOverview_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ціна.
        /// </summary>
        public static string Page1_Price_tabel {
            get {
                return ResourceManager.GetString("Page1_Price_tabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Огляд.
        /// </summary>
        public static string Page1_Review_tabel {
            get {
                return ResourceManager.GetString("Page1_Review_tabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва.
        /// </summary>
        public static string Page1_Title_tabel {
            get {
                return ResourceManager.GetString("Page1_Title_tabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обсяг (24г).
        /// </summary>
        public static string Page1_Volume24h_tabel {
            get {
                return ResourceManager.GetString("Page1_Volume24h_tabel", resourceCulture);
            }
        }
    }
}
